---
driver_plugin: vagrant
driver_config:
  customize:
    memory: 1024

provisioner:
  name: chef_zero
  chef_client:

platforms:
  - name: ubuntu-12.04
    run_list:
    - recipe[apt::default]
  - name: centos-6.4
   
suites:
  - name: default
    encrypted_data_bag_secret_key_path: 'test/integration/default/encrypted_data_bag_secret'
    driver_config:
      network:
      - ['forwarded_port', {guest: 80, host: 8081}]
    run_list:
      - recipe[wrapper-redmine::default]
      - recipe[gitlab::default]
    attributes:
      mysql:
        server_root_password: 'rootpass'
        server_debian_password: 'debpass'
        server_repl_password: 'replpass'
        bind_address: 'localhost'
      redmine:
        database:
          password: 'redmine'
    excludes:
      - centos-6.4
